spring:
  data:
    mongodb:
      uri : mongodb+srv://vaibhavsingh:1234abcd@cluster0.x2hwkl9.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database : journaldb
      auto-index-creation : true


server  :
  port : 8080
  servlet :
    context-path: /journal

gemini:
  api:
    key: AIzaSyDbwKiGyww_1fn4gwUIUjdRBjxwxwgSCC8
    url: https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent



#logging:
#  level:
#    root: ERROR

